### ISSUE TITLE
Trig Tour Master Checklist

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/trig-tour#1]
## Design
- [x] **Design doc created** (Date: 05/26/2015) 
  - [x] Shared with phet-team, phethelp@gmail is owner
- [x] **Learning goals and standards identified** (Date: 06/08/2015)
- [x] **Design concept complete**  (Date: 06/04/2015)
- [x] **Wireframes complete** (Date: 06/09/2015) 
- [x] **Mockups complete** (Date: 07/02/2015) 
  - [x] Mockups checked for colorblind and greyscale
- [x] **Interviews complete** (Date: 8/11/15) 
  - [x] Results reported to team
  - [x] Notes pasted into design doc
  - [x] Back-up of interviews
- [x] **Lead designer "sign off"** (Date: 02/03/2016) 
  - [x] Performance acceptable
  - [x] Carefully review ?showPointerAreas
  - [x] No new feature requests
- [x] **Pre-publication items** 
  - [x] Screenshot (2048x1344, PNG, 32-bit color, browser chrome stripped)
  - [x] Accessories (keywords, categories, description, learning goals, related sims, NSDL)
  - [x] Teacher Tips
  - [x] Add an activity
  - [x] Update [Gooru spreadsheet](https://docs.google.com/spreadsheets/d/13qvc7e71zTTjaJ2VcYhhU0rNxvH4kYFnoScVCOvvf7U/edit#gid=1717560774)
  - [ ] Sim primer
  - [x] Verify credits
- [x] **Add to Edmodo**
## Implementation
- [x] **Sim repo created** (Date: 05/22/2015) 
  - [x] Collaborators added (such as QA team, designers, etc) 
  - [x] Sim added to active repos list in chipper
  - [x] Sim suggestions doc reviewed
  - [x] Port existing strings (IF ANY) and commit to the GitHub repo
- [x] **Initial development started** (Date: 05/27/2015)
- [x] **Sim feature complete** (Date: 07/20/2015) 
- [x] **Code review complete** (Date: 10/09/2015) 
  - [x] Code review checklist
  - [x] Model description 
- [x] **Published** (Date: 02/08/2016) 
  - [x] Update repo README to published template
## QA
- [x] **Dev testing complete** (Date: 10/21/2015) 
- [x] **First release candidate** (Date: 01/29/2016) 
  - [x] phethelp@gmail.com owner of test matrix, share with phet-team, add to [Master Doc List](https://docs.google.com/document/d/1yjT1oE95JG_evwob9LB_De-brD7JpfFM6iIL6pF812k/edit#)
  - [x] Test matrix deemed complete

**Comment by ariel-phet** [comment]
@jessegreenberg please make phethelp the owner of the test matrix

**Comment by jessegreenberg** [comment]
Made new matrix under gmail domain and it is owned by phethelp.  Reassigning to @ariel-phet.

**Comment by phet-steele** [comment]
@ariel-phet @amanda-phet @jessegreenberg sim is visible!

**Comment by ariel-phet** [comment]
Awesome!...and it already has 3 translations!

**Comment by ariel-phet** [comment]
@jessegreenberg can you finish off the implementation steps (changing read-me and model description) then reassign to me?

**Comment by jessegreenberg** [comment]
New readme generated and model.md was done as part of the code review. Reassigning to @ariel-phet.
